# Generated by Django 6.0.3 on 2026-03-15 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRole",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#94a3b8", max_length=7)),
                ("permissions", models.JSONField(default=list)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventScheduleDay",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("day_index", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventStaff",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("poster", "Poster"),
                            ("resume", "Resume"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("file_url", models.URLField()),
                ("file_key", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("size_bytes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("hackathon", "Hackathon"),
                            ("seminar", "Seminar"),
                            ("workshop", "Workshop"),
                            ("conference", "Conference"),
                            ("meetup", "Meetup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("pending_approval", "Pending Approval"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("college_only", "College Only"),
                            ("invite_only", "Invite Only"),
                            ("private_link", "Private Link"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("registration_start", models.DateTimeField(blank=True, null=True)),
                ("registration_end", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                ("current_participants", models.IntegerField(default=0)),
                ("banner_image_url", models.URLField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("allow_teams", models.BooleanField(default=False)),
                ("team_min_size", models.IntegerField(default=1)),
                ("team_max_size", models.IntegerField(default=4)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                (
                    "venue_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("venue_room", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "online_platform",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("meeting_link", models.URLField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "fee_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("payment_deadline_at", models.DateTimeField(blank=True, null=True)),
                ("certificates_enabled", models.BooleanField(default=False)),
                ("certificate_template_url", models.URLField(blank=True, null=True)),
                (
                    "attendance_method",
                    models.CharField(
                        choices=[("qr", "QR Code"), ("manual", "Manual")],
                        default="qr",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="clubs.club",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistrationField",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("date", "Date"),
                            ("select", "Select"),
                            ("multiselect", "Multi-select"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                            ("textarea", "Text Area"),
                            ("file", "File"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("help_text", models.TextField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("validation", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_fields",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistrationResponse",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_number", models.IntegerField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_file_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_responses",
                        to="events.event",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="events.eventregistrationfield",
                    ),
                ),
            ],
        ),
    ]
