# Generated by Django 6.0.3 on 2026-03-15 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("overall_rating", models.IntegerField()),
                ("organization_rating", models.IntegerField()),
                ("venue_rating", models.IntegerField()),
                ("content_rating", models.IntegerField()),
                ("would_recommend", models.BooleanField()),
                ("feedback_text", models.TextField(blank=True, null=True)),
                ("improvements", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("message_text", models.TextField(blank=True, null=True)),
                ("file_url", models.URLField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_type", models.CharField(blank=True, max_length=100, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("reminder", "Reminder"),
                            ("announcement", "Announcement"),
                            ("message", "Message"),
                            ("task", "Task"),
                            ("achievement", "Achievement"),
                            ("registration", "Registration"),
                            ("score", "Score"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("action_url", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=36, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("update", "Update"),
                            ("urgent", "Urgent"),
                            ("reminder", "Reminder"),
                            ("info", "Info"),
                            ("achievement", "Achievement"),
                        ],
                        default="update",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("committee", "Committee"),
                            ("participants", "Participants"),
                            ("volunteers", "Volunteers"),
                            ("judges", "Judges"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("read_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
